# Generated by Django 4.1.1 on 2022-09-17 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('buyout', models.FloatField(null=True)),
                ('start_bid', models.FloatField()),
                ('listing_day', models.DateField()),
                ('listing_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Listing_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.CharField(max_length=512)),
                ('image_2', models.CharField(max_length=512)),
                ('image_3', models.CharField(max_length=512)),
                ('image_4', models.CharField(max_length=512)),
                ('image_5', models.CharField(max_length=512)),
                ('listing_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_listing_image', to='auctions.listings')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_day', models.DateField()),
                ('comment_time', models.TimeField()),
                ('comment_content', models.CharField(max_length=256)),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenting_user', to=settings.AUTH_USER_MODEL)),
                ('listing_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_listing_comment', to='auctions.listings')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField()),
                ('bid_day', models.DateField()),
                ('bid_time', models.TimeField()),
                ('bid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_user', to=settings.AUTH_USER_MODEL)),
                ('listing_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_listing_bid', to='auctions.listings')),
            ],
        ),
    ]
