# Generated by Django 4.1.1 on 2022-09-21 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='day',
            field=models.DateField(default=datetime.date(2022, 9, 21)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 21, 20, 7, 16, 254112, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 21, 20, 7, 24, 873147, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingcomment',
            name='day',
            field=models.DateField(default=datetime.date(2022, 9, 21)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingcomment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 21, 20, 7, 42, 302243, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
