# Generated by Django 4.1.1 on 2022-09-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_listing_images_comments_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='listing_status',
            field=models.CharField(default='Open', max_length=6),
        ),
    ]
