# Generated by Django 4.1.1 on 2022-09-18 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watch_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listing_bid',
        ),
        migrations.RemoveField(
            model_name='listing_images',
            name='listing_image',
        ),
        migrations.AddField(
            model_name='bids',
            name='listing_bid_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing_images',
            name='listing_images_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.listings'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenting_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='listing_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='watch_list',
            name='listing_watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_occurrences', to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='watch_list',
            name='watchlist_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
