# Generated by Django 4.1.1 on 2022-09-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch_list',
            name='listing_watchlist',
        ),
        migrations.AddField(
            model_name='watch_list',
            name='listing_watchlist',
            field=models.ManyToManyField(related_name='watchlist_occurrences', to='auctions.listings'),
        ),
    ]
