# Generated by Django 4.1.1 on 2022-09-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_watch_list_listing_watchlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch_list',
            name='listing_watchlist',
        ),
        migrations.AddField(
            model_name='watch_list',
            name='listing_watchlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_occurrences', to='auctions.listings'),
            preserve_default=False,
        ),
    ]
