# Generated by Django 4.1.1 on 2022-09-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_watch_list_listing_watchlist_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing_images',
            new_name='ListingImages',
        ),
        migrations.RenameModel(
            old_name='Watch_list',
            new_name='Watchlist',
        ),
    ]
